ingress:
  enabled: true
  className: "traefik"
  host: "onedev.uaiso.lan"

database:
  external: true
  type: "postgresql"
  host: "postgresql.postgresql.svc.cluster.local"
  port: "5432"
  name: "onedev"
  user: "postgres"
  password: "mysecurepassword"

service:
  separateSSH:
    enabled: true
    type: "LoadBalancer"
    port: 22
